```{r}
library(ggplot2)
library(ggsci)
library(RColorBrewer)
library(gg.gap)
```

# f

```{r}
data=readRDS(file='Fig1.f.rds')

ggplot(data = data, mapping = aes(x = Region, y = OR,fill=label)) + 
  geom_bar(stat = 'identity',position = "dodge") +
  xlab("") +
  ylab("Odds Ratio") +
  scale_fill_manual(values=c('#f56766','#7eaedc'))+
  scale_y_continuous(breaks=c(-1,0,1,2,3,4,5,6,7,8,9),labels=c(0,1,2,3,4,5,6,7,8,9,10))+
  theme_bw() +
  theme(axis.title = element_text(size = 14),
        axis.text = element_text(size = 13),
        panel.grid.major=element_line(color="white"),
        panel.grid.minor=element_line(color="white"),
        axis.line=element_line(color="black"),
        axis.text.x = element_text(angle = 60, hjust = 0.5, vjust = 0.5),
        legend.title = element_blank(),
        legend.position = 'none')
```

# g

```{r}
data=readRDS(file='Fig1.g.rds')

ggplot(data = data, mapping = aes(x = Region, y = OR,fill=label)) + 
  geom_bar(stat = 'identity',position = "dodge") +
  xlab("") +
  ylab("Odds Ratio") +
  scale_fill_manual(values=c('#f56766','#7eaedc'))+
  scale_y_continuous(breaks=c(-1,0,1,2,3,4,5,6,7,8,9,10,11),labels=c(0,1,2,3,4,5,6,7,8,9,10,11,12))+
  theme_bw() +
  theme(axis.title = element_text(size = 14),
        axis.text = element_text(size = 13),
        panel.grid.major=element_line(color="white"),
        panel.grid.minor=element_line(color="white"),
        axis.line=element_line(color="black"),
        axis.text.x = element_text(angle = 60, hjust = 0.5, vjust = 0.5),
        legend.title = element_blank())
```

# h

```{r}
data=readRDS(file='Fig1.h.rds')

p1=ggplot(data = data, mapping = aes(x = Region, y = OR,fill=label)) + 
  geom_bar(stat = 'identity',position = "dodge") +
  xlab("") +
  ylab("Odds Ratio") +
  scale_fill_lancet()+
  scale_y_continuous(breaks=c(-1,0,1,2,3,4,9,14,19),labels=c(0,1,2,3,4,5,10,15,20))+
  theme_bw() +
  theme(axis.title = element_text(size = 14),
        axis.text = element_text(size = 13),
        panel.grid.major=element_line(color="white"),
        panel.grid.minor=element_line(color="white"),
        axis.line=element_line(color="black"),
        axis.text.x = element_text(angle = 60, hjust = 0.5, vjust = 0.5),
        legend.title = element_blank(),
        legend.position = 'none')

p1+theme_classic()
```

# i

```{r}
data=readRDS(file='Fig1.i.rds')

p1=ggplot(data = data, mapping = aes(x = Region, y = OR,fill=label)) + 
  geom_bar(stat = 'identity',position = "dodge") +
  xlab("") +
  ylab("Odds Ratio") +
  scale_fill_lancet()+
  scale_y_continuous(breaks=c(-1,0,1,2,3,9,14,19),labels=c(0,1,2,3,4,10,15,20))+
  theme_bw() +
  theme(axis.title = element_text(size = 14),
        axis.text = element_text(size = 13),
        panel.grid.major=element_line(color="white"),
        panel.grid.minor=element_line(color="white"),
        #panel.border=element_blank(),
        axis.line=element_line(color="black"),
        axis.text.x = element_text(angle = 60, hjust = 0.5, vjust = 0.5),
        legend.title = element_blank(),
        legend.position = 'none')

p1+theme_classic()
```
