```{r}
library(RColorBrewer)
library(ggrepel)
library(ggplot2)
library(hrbrthemes)
library(dplyr)
library(ggthemes)
```

# a

```{r}
data=readRDS(file='Fig2a.rds')
p <- d %>%
      ggplot() +
              geom_point(aes(x=-log10(posXnspt), y=-log10(posYcas),color = direction)) +
              geom_point(aes(x=-log10(negXnspt), y=-log10(negYcas),color = direction)) +
              labs(x = "p value in NSPT", y = "p value in CAS", color="-log10(p value )",title = "")+
              scale_colour_manual(values=cpgcolor) +
              ggrepel::geom_label_repel( data=d %>% filter(cpg %in% cpg_label) %>% filter(direction == "positive"), aes(x=-log10(whiteP.nspt), y= -log10(whiteP.cas), label=SYMBOL), alpha=1, size=4,color = "#FF99CC",max.overlaps=20)+
              ggrepel::geom_label_repel( data=d %>% filter(cpg %in% cpg_label)%>% filter(direction == "negative"), aes(x=-log10(whiteP.nspt), y= -log10(whiteP.cas), label=SYMBOL), alpha=1, size=4,color = "#99CCFF",max.overlaps=20)+
              geom_vline(xintercept = c(-log10(thres)),color = "#990000", linetype="dashed")+
              geom_hline(yintercept=c(-log10(0.05)),color = "#990000", linetype="dashed")+
              theme_few()+
              theme(axis.text.x = element_text(vjust = 0.5, hjust=0.5,face="bold", size=15,color = "black"),
                    axis.text.y = element_text(size=15, face="bold", color = "black"),
                    axis.title.x =element_text(face="bold", size=15, color = "black",hjust=0.5),
                    axis.title.y =element_text(face="bold", size=15, color = "black",hjust=0.5),
                    plot.title = element_text(hjust=0.5, face="bold"),
                    panel.grid.major=element_blank(),
                    panel.grid.minor=element_blank(),
                    panel.border=element_rect(color="black", fill = NA, size=1))
p
```

# b c 

```{r}
usedplot=readRDS(file='Fig2bc.rds')
usedplot$sample <- factor(usedplot$sample, levels=c("NSPT", "CAS"))
sample_colors <- c("#B10026", "#097cbe")
names(sample_colors) <- c("NSPT", "CAS")
run_scale <- function(x) sprintf("%.2f", x)
date=format(Sys.time(), format="%y-%B-%d")
dir.create("Fig2")

p_point_cg04457792 <- ggplot(data=usedplot,aes(x=Age, y=cg24035745, color=sample)) +
                      geom_point(size = 1.5) +
                      xlab("Age") + ylab("DNA methylation levels of cg24035745")+
                      theme_bw() +
                      scale_color_manual(values = sample_colors)  +
                      scale_y_continuous(labels=run_scale)+
                      theme(axis.ticks.length.x=unit(0.15, "cm"),
                      axis.ticks.length.y=unit(0.15, "cm"),
                      axis.text.x = element_text(face="bold", size=15,color = "black"),
                      axis.text.y = element_text(size=15, face="bold", color = "black"),
                      axis.title.x =element_text(face="bold", size=15, color = "black", vjust = 0.1),
                      axis.title.y =element_text(face="bold", size=15, color = "black", vjust = 0.1)) +
                      theme(plot.title = element_text(hjust=0.5, face="bold")) +
                      theme(legend.text = element_text(color = "black", size = 15))

ggsave(filename = paste0('Fig2/',date,'_pscatter_cg24035745.pdf'),plot = p_point_cg04457792, width=6,height = 6)

p_point_cg13868026 <- ggplot(data=usedplot,aes(x=Age, y=cg13868026, color=sample)) +
                      geom_point(size = 1.5) +
                      xlab("Age") + ylab("DNA methylation levels of cg13868026")+
                      theme_bw() +
                      scale_color_manual(values = sample_colors)  +
                      theme(axis.ticks.length.x=unit(0.15, "cm"),
                      axis.ticks.length.y=unit(0.15, "cm"),
                      axis.text.x = element_text(face="bold", size=15,color = "black"),
                      axis.text.y = element_text(size=15, face="bold", color = "black"),
                      axis.title.x =element_text(face="bold", size=15, color = "black", vjust = 0.1),
                      axis.title.y =element_text(face="bold", size=15, color = "black", vjust = 0.1)) +
                      theme(plot.title = element_text(hjust=0.5, face="bold")) +
                      theme(legend.text = element_text(color = "black", size = 15))

ggsave(filename = paste0('Fig2/',date,'_pscatter_cg13868026.pdf'),plot = p_point_cg13868026,width=6,height = 6)
```

# d 
```{r}
usedplot <- readRDS("Fig2d.rds")
# 3. 正负漂移分类 先绘制阳性 在绘制阴性的点
cpgcolor=c("#FF99CC", "#99CCFF")
names(cpgcolor)=c("positive", "negative")

p <-  ggplot(data=usedplot, aes(x=-log10(whiteP.cas), y=-log10(p)),color=direction) +
             geom_point(aes(x=-log10(whiteP.cas), y=-log10(p)), size = 1.5,  data = usedplot[usedplot$direction == "positive",],color="#FF99CC") +
             geom_point(aes(x=-log10(whiteP.cas), y=-log10(p)), size = 1.5,  data = usedplot[usedplot$direction == "negative",],color="#99CCFF") +
             labs(y = "p value in Changfeng", x = "p value in CAS", color="-log10(p)",title = "")+
             scale_x_continuous(breaks = seq(0,10,2.5))+
             ggrepel::geom_label_repel( data=usedplot %>% filter(cpg %in% cpg_label) %>% filter(direction == "positive"), aes(x=-log10(whiteP.cas), y=-log10(p), label=SYMBOL), alpha=1, size=4,color = "#FF99CC",max.overlaps=20)+
             ggrepel::geom_label_repel( data=usedplot %>% filter(cpg %in% cpg_label)%>% filter(direction == "negative"), aes(x=-log10(whiteP.cas), y=-log10(p), label=SYMBOL), alpha=1, size=4,color = "#99CCFF",max.overlaps=20)+
	         geom_vline(xintercept = c(-log10(0.05)),color = "#990000", linetype="dashed")+
	         geom_hline(yintercept = c(-log10(0.05)),color = "#990000", linetype="dashed")+
  	         ggthemes::theme_few()+ #vjust1右对齐，face粗体，angle=倾斜
	         theme(axis.text.x = element_text(vjust = 0.5, hjust=0.5,face="bold", size=15,color = "black"),
	               axis.text.y = element_text(size=15, face="bold", color = "black"),
		           axis.title.x =element_text(face="bold", size=15, color = "black",hjust=0.5),
		           axis.title.y =element_text(face="bold", size=15, color = "black",hjust=0.5),
                   plot.title = element_text(hjust=0.5, face="bold"),
		           panel.grid.major=element_blank(),
	               panel.grid.minor=element_blank(),
		           panel.border=element_rect(color="black", fill = NA, size=1))
```

# e f 
```{r}
usedplot <- readRDS("Fig2ef.rds")
sample_colors <- c("#c4bcc4", "#FF99CC")
names(sample_colors) <- c("Baseline", "Follow-up")

run_scale <- function(x) sprintf("%.2f", x)
p_point_cg21572722 <- ggplot(data=usedplot,aes(x=Age, y=cg21572722, color=sample)) +
                      geom_point(aes(x = Age, y =cg21572722), size = 1.5, na.rm = TRUE, data = usedplot[usedplot$sample == "Baseline",])+
                      geom_point(aes(x = Age, y =cg21572722), size = 1.5, na.rm = TRUE, data = usedplot[usedplot$sample == "Follow-up",])+
                      xlab("Age") + ylab("DNA methylation levels of cg21572722")+
                      theme_bw() +
                      scale_color_manual(values = sample_colors)  +
                      scale_y_continuous(labels=run_scale)+              
                      theme(axis.ticks.length.x=unit(0.15, "cm"),
                      axis.ticks.length.y=unit(0.15, "cm"),
                      axis.text.x = element_text(face="bold", size=15,color = "black"),
                      axis.text.y = element_text(size=15, face="bold", color = "black"),
                      axis.title.x =element_text(face="bold", size=15, color = "black", vjust = 0.1),
                      axis.title.y =element_text(face="bold", size=15, color = "black", vjust = 0.1)) +
                      theme(plot.title = element_text(hjust=0.5, face="bold")) +
                      theme(legend.text = element_text(color = "black", size = 15))

ggsave(filename = paste0('Fig2/',date,'Changfeng_pscatter_baseline_followup_cg21572722.pdf'),plot = p_point_cg21572722, width=6,height = 6)


#散点图 负漂移
sample_colors <- c("#c4bcc4", "#99CCFF")
names(sample_colors) <- c("Baseline", "Follow-up")

p_point_cg14520079 <- ggplot(data=usedplot,aes(x=Age, y=cg14520079, color=sample)) +
                      geom_point(aes(x = Age, y =cg14520079), size = 1.5, na.rm = TRUE, data = usedplot[usedplot$sample == "Baseline",])+
                      geom_point(aes(x = Age, y =cg14520079), size = 1.5, na.rm = TRUE, data = usedplot[usedplot$sample == "Follow-up",])+
                      xlab("Age") + ylab("DNA methylation levels of cg14520079")+
                      theme_bw() +
                      scale_color_manual(values = sample_colors)  +
                      scale_y_continuous(labels=run_scale)+
                      theme(axis.ticks.length.x=unit(0.15, "cm"),
                      axis.ticks.length.y=unit(0.15, "cm"),
                      axis.text.x = element_text(face="bold", size=15,color = "black"),
                      axis.text.y = element_text(size=15, face="bold", color = "black"),
                      axis.title.x =element_text(face="bold", size=15, color = "black", vjust = 0.1),
                      axis.title.y =element_text(face="bold", size=15, color = "black", vjust = 0.1)) +
                      theme(plot.title = element_text(hjust=0.5, face="bold")) +
                      theme(legend.text = element_text(color = "black", size = 15))

#保存
ggsave(filename = paste0('Fig2/',date,'Changfeng_pscatter_baseline_followup_cg14520079.pdf'),plot = p_point_cg14520079,width=6,height = 6)
saveRDS(usedplot, file=paste0('Fig2/',date,'Changfeng_pscatter_baseline_followup_cg16532606_cg14520079.rds'))

```

# g

```{r}
d=readRDS(file='Fig2g.rds')
d <- d[which(d$whiteP.GSE40279 < 0.05),]
p <- d %>%
  	ggplot() +
          geom_point(aes(x=-log10(posXcas), y=-log10(posYGSE40279),color = direction)) +
          geom_point(aes(x=-log10(negXcas), y=-log10(negYGSE40279),color = direction))  +
	      labs(y = "p value in Hannum et al.", x = "p value in CAS", color="-log10(p)",title = "")+
          scale_colour_manual(values=cpgcolor) +
          ggrepel::geom_label_repel( data=d %>% filter(cpg %in% cpg_label) %>% filter(direction == "positive"), aes(x=-log10(posXcas), y=-log10(posYGSE40279), label=SYMBOL), alpha=1, size=4,color = "#FF99CC",max.overlaps=20)+
          ggrepel::geom_label_repel( data=d %>% filter(cpg %in% cpg_label)%>% filter(direction == "negative"), aes(x=-log10(negXcas), y=-log10(negYGSE40279), label=SYMBOL), alpha=1, size=4,color = "#99CCFF",max.overlaps=20)+
          geom_vline(xintercept = c(-log10(0.05)),color = "#990000", linetype="dashed")+
	      geom_hline(yintercept = c(-log10(0.05)),color = "#990000", linetype="dashed")+
  	      ggthemes::theme_few()+ #vjust1右对齐，face粗体，angle=倾斜
	      theme(axis.text.x = element_text(vjust = 0.5, hjust=0.5,face="bold", size=15,color = "black"),
	            axis.text.y = element_text(size=15, face="bold", color = "black"),
		        axis.title.x =element_text(face="bold", size=15, color = "black",hjust=0.5),
		        axis.title.y =element_text(face="bold", size=15, color = "black",hjust=0.5),
                plot.title = element_text(hjust=0.5, face="bold"),
		        panel.grid.major=element_blank(),
	            panel.grid.minor=element_blank(),
		        panel.border=element_rect(color="black", fill = NA, size=1))
```

# h i 
```{r}
usedplot <- readRDS("Fig2hi.rds")
p_point_cg16532606 <- ggplot(data=usedplot,aes(x=Age, y=cg16532606, color=sample)) +
                      geom_point(aes(x = Age, y =cg16532606), size = 1.5, na.rm = TRUE, data = usedplot[usedplot$sample == "NSPT",])+
                      geom_point(aes(x = Age, y =cg16532606), size = 1.5, na.rm = TRUE, data = usedplot[usedplot$sample == "CAS",])+
                      geom_point(aes(x = Age, y =cg16532606), size = 1.5, na.rm = TRUE, data = usedplot[usedplot$sample == "Hannum",])+
                      xlab("Age") + ylab("DNA methylation levels of cg16532606")+
                      theme_bw() +
                      scale_color_manual(values = sample_colors)  +
                      scale_y_continuous(labels=run_scale)+              
                      theme(axis.ticks.length.x=unit(0.15, "cm"),
                      axis.ticks.length.y=unit(0.15, "cm"),
                      axis.text.x = element_text(face="bold", size=15,color = "black"),
                      axis.text.y = element_text(size=15, face="bold", color = "black"),
                      axis.title.x =element_text(face="bold", size=15, color = "black", vjust = 0.1),
                      axis.title.y =element_text(face="bold", size=15, color = "black", vjust = 0.1)) +
                      theme(plot.title = element_text(hjust=0.5, face="bold")) +
                      theme(legend.text = element_text(color = "black", size = 15))

ggsave(filename = paste0('Fig2/',date,'Hannum_CAS_NSPT_pscatter_cg16532606.pdf'),plot = p_point_cg16532606, width=6,height = 6)


#散点图 负漂移
p_point_cg11647481 <- ggplot(data=usedplot,aes(x=Age, y=cg11647481, color=sample)) +
                      geom_point(aes(x = Age, y =cg11647481), size = 1.5, na.rm = TRUE, data = usedplot[usedplot$sample == "NSPT",])+
                      geom_point(aes(x = Age, y =cg11647481), size = 1.5, na.rm = TRUE, data = usedplot[usedplot$sample == "CAS",])+
                      geom_point(aes(x = Age, y =cg11647481), size = 1.5, na.rm = TRUE, data = usedplot[usedplot$sample == "Hannum",])+
                      xlab("Age") + ylab("DNA methylation levels of cg11647481")+
                      theme_bw() +
                      scale_color_manual(values = sample_colors)  +
                      scale_y_continuous(labels=run_scale)+
                      theme(axis.ticks.length.x=unit(0.15, "cm"),
                      axis.ticks.length.y=unit(0.15, "cm"),
                      axis.text.x = element_text(face="bold", size=15,color = "black"),
                      axis.text.y = element_text(size=15, face="bold", color = "black"),
                      axis.title.x =element_text(face="bold", size=15, color = "black", vjust = 0.1),
                      axis.title.y =element_text(face="bold", size=15, color = "black", vjust = 0.1)) +
                      theme(plot.title = element_text(hjust=0.5, face="bold")) +
                      theme(legend.text = element_text(color = "black", size = 15))

#保存
ggsave(filename = paste0('Fig2/',date,'Hannum_CAS_NSPT__pscatter_cg11647481.pdf'),plot = p_point_cg11647481,width=6,height = 6)
saveRDS(usedplot, file=paste0('Fig2/',date,'Hannum_CAS_NSPT__pscatter_cg16532606_cg11647481.rds'))
```

# j
```{r}
usedplot <- readRDS("Fig2j.rds")
p <- d %>%
      ggplot() +
              geom_point(aes(x=beta, y=-log10(p),color = direction)) +
              labs(x = "beta in Twins", y = "p value in Twins", color="-log10(p value )",title = "")+
              scale_colour_manual(values=cpgcolor) +
              ggrepel::geom_label_repel( data=d %>% filter(cpg %in% cpg_label) %>% filter(direction == "positive"), aes(x=beta, y= -log10(p), label=gene), alpha=1, size=4,color = "#FF99CC",max.overlaps=20)+
              ggrepel::geom_label_repel( data=d %>% filter(cpg %in% cpg_label)%>% filter(direction == "negative"), aes(x=beta, y= -log10(p), label=gene), alpha=1, size=4,color = "#99CCFF",max.overlaps=20)+
              geom_vline(xintercept = 0,color = "#990000", linetype="dashed")+
              geom_hline(yintercept=c(-log10(0.05)),color = "#990000", linetype="dashed")+
              theme_few()+
              theme(axis.text.x = element_text(vjust = 0.5, hjust=0.5,face="bold", size=15,color = "black"),
                    axis.text.y = element_text(size=15, face="bold", color = "black"),
                    axis.title.x =element_text(face="bold", size=15, color = "black",hjust=0.5),
                    axis.title.y =element_text(face="bold", size=15, color = "black",hjust=0.5),
                    plot.title = element_text(hjust=0.5, face="bold"),
                    panel.grid.major=element_blank(),
                    panel.grid.minor=element_blank(),
                    panel.border=element_rect(color="black", fill = NA, size=1))
p


```


# k l 
```{r}
usedplot <- readRDS("Fig2kl.rds")
run_scale <- function(x) sprintf("%.2f", x)
cpgcolor=c("#FF99CC", "#99CCFF")

p_point_cg21109038 <- ggplot(data=usedplot,aes(x=age, y=cg21109038)) +
                      geom_point(size = 1.5,color=cpgcolor[1]) +
                      xlab("Age") + ylab("DNA methylation levels of cg21109038")+
                      theme_bw() +
                      scale_y_continuous(labels=run_scale)+
                      theme(axis.ticks.length.x=unit(0.15, "cm"),
                      axis.ticks.length.y=unit(0.15, "cm"),
                      axis.text.x = element_text(face="bold", size=15,color = "black"),
                      axis.text.y = element_text(size=15, face="bold", color = "black"),
                      axis.title.x =element_text(face="bold", size=15, color = "black", vjust = 0.1),
                      axis.title.y =element_text(face="bold", size=15, color = "black", vjust = 0.1)) +
                      theme(plot.title = element_text(hjust=0.5, face="bold")) +
                      theme(legend.text = element_text(color = "black", size = 15))

ggsave(filename = paste0('Fig2/',date,'_twins_pscatter_cg21109038.pdf'),plot = p_point_cg21109038, width=6,height = 6)

p_point_cg08337633 <- ggplot(data=usedplot,aes(x=age, y=cg08337633)) +
                      geom_point(size = 1.5, color=cpgcolor[2]) +
                      xlab("Age") + ylab("DNA methylation levels of cg08337633")+
                      theme_bw() +
                      theme(axis.ticks.length.x=unit(0.15, "cm"),
                      axis.ticks.length.y=unit(0.15, "cm"),
                      axis.text.x = element_text(face="bold", size=15,color = "black"),
                      axis.text.y = element_text(size=15, face="bold", color = "black"),
                      axis.title.x =element_text(face="bold", size=15, color = "black", vjust = 0.1),
                      axis.title.y =element_text(face="bold", size=15, color = "black", vjust = 0.1)) +
                      theme(plot.title = element_text(hjust=0.5, face="bold")) +
                      theme(legend.text = element_text(color = "black", size = 15))

ggsave(filename = paste0('Fig2/',date,'_twin_pscatter_cg08337633.pdf'),plot = p_point_cg08337633,width=6,height = 6)


```

