```{r}
library(ggplot2)
library(patchwork)

phen=readRDS(file='Fig.7.rds')
```


# c

```{r}
ggplot(phen, aes(x=rs7868942, y=EDS204_scale120)) + 
  geom_boxplot(outlier.shape = NA,,fill='#FF99CC')+
  ylim(0.2,0.65)+
  xlab('')+
  ylab('EDS(positive)')+
  labs(title='rs7868942')+
  theme_bw() +
  theme(axis.title = element_text(size = 20),
        axis.text = element_text(size = 20),
        panel.grid.major=element_line(color="white"),
        panel.grid.minor=element_line(color="white"),
        panel.border=element_blank(),
        axis.line=element_line(color="black"),
        legend.position = 'none',
        plot.title = element_text(hjust = 0.5,size=25))
```

# g

```{r}
ggplot(phen, aes(x=rs76089707, y=EDS81_scale120)) + 
  geom_boxplot(outlier.shape = NA, fill='#99CCFF')+
  ylim(0.2,0.6)+
  xlab('')+
  ylab('EDS(negative)')+
  labs(title='rs76089707')+
  theme_bw() +
  theme(axis.title = element_text(size = 20),
        axis.text = element_text(size = 20),
        panel.grid.major=element_line(color="white"),
        panel.grid.minor=element_line(color="white"),
        panel.border=element_blank(),
        axis.line=element_line(color="black"),
        legend.position = 'none',
        plot.title = element_text(hjust = 0.5,size=25))
```
